### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by Birdehub** [adein/hangouts_to_sms#13]
I made the changes mentioned in #8 and received the same error as I did the first time I ran it without the changes.  If it matters, my json is 222,683KB in size.

**OUTPUT:**

C:\hangouts_to_sms-develop\hangouts_to_sms-develop>hangouts_to_sms.py
Parsing Hangouts data file...
Traceback (most recent call last):
  File "C:\hangouts_to_sms-develop\hangouts_to_sms.py", line 15, in <module>
    conversations, self_gaia_id = hangouts_parser.parse_input_file(HANGOUTS_JSON_FILE, YOUR_PHONE_NUMBER)
  File "C:\hangouts_to_sms-develop\hangouts_parser.py", line 23, in parse_input_file
    data = json.load(data_file, object_hook=lambda d: Namespace(**d))
  File "C:\Users\Me\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 349, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
MemoryError

**Comment by gbrown2036** [comment]
I'm getting the same thing with my 258mb hangouts.json file.  Was the 3rd party JSON parser for Python that can parse as an input stream ever added?  If not, does anyone know what needs to be changed?  Thanks

**Comment by GamerKingFaiz** [comment]
I'm getting a separate error after making the changes in #8.

**OUTPUT:**  
Traceback (most recent call last):
  File "C:\hangouts_to_sms-develop\hangouts_to_sms.py", line 1, in <module> from hangouts_parser import HangoutsParser
  File "C:\Users\Faiz-ur.Rahman\Downloads\hangouts_to_sms-develop\hangouts_parser.py", line 2, in <module>
    from argparse import Namespace
ImportError: No module named argparse

Excuse my ignorance if this is just a simple Python mistake...
