### ISSUE TITLE
ImportError: No module named argparse

### ISSUE THREAD

**Issue by GamerKingFaiz** [adein/hangouts_to_sms#14]
I'm getting a separate error after making the changes in #8.

**OUTPUT:**  
Traceback (most recent call last):
  File "C:\hangouts_to_sms-develop\hangouts_to_sms.py", line 1, in <module> from hangouts_parser import HangoutsParser
  File "C:\Users\Faiz-ur.Rahman\Downloads\hangouts_to_sms-develop\hangouts_parser.py", line 2, in <module>
    from argparse import Namespace
ImportError: No module named argparse

Excuse my ignorance if this is just a simple Python mistake...

**Comment by GamerKingFaiz** [comment]
Uninstalling Python 3.0 and installing the latest version (Python 3.6.5) seemed to have gotten me past this error.
