### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by JoesphG** [adein/hangouts_to_sms#17]
Looked at the suggestions in #12 but still get issues below @mrdehate

>C:\sms\hangouts_to_sms-develop>python hangouts_to_sms.py
Traceback (most recent call last):
  File "hangouts_to_sms.py", line 2, in <module>
    from titanium_backup_formatter import TitaniumBackupFormatter
  File "C:\sms\hangouts_to_sms-develop\titanium_backup_formatter.py", line 83
    message_string += "{}".format(escape(message.content) if content_is_plain else self._base64_text(message.content))
                                                                                                                     ^
TabError: inconsistent use of tabs and spaces in indentation

here is the code snippet

![image](https://user-images.githubusercontent.com/31412986/42667420-4a3e085e-8600-11e8-94e0-e1f0387ffbb7.png)

**Comment by JoesphG** [comment]
replaced all tabs with 4 spaces in file to resolve issue

**Comment by JoesphG** [comment]
Using reindent.py
