### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by JoesphG** [adein/hangouts_to_sms#18]
Hi all, any ideas as to resolving this problem?

```
C:\sms\hangouts_to_sms-develop>python` hangouts_to_sms.py
Parsing Hangouts data file...
Done.
Converting to SMS export file...
Error: could not match sender gaia ID to participant IDs!
Error: could not match sender gaia ID to participant IDs!
Error: could not match sender gaia ID to participant IDs!
Error: could not match sender gaia ID to participant IDs!
Error: could not match sender gaia ID to participant IDs!
Error: could not match sender gaia ID to participant IDs!
Error: could not match sender gaia ID to participant IDs!
Error: could not match sender gaia ID to participant IDs!
Traceback (most recent call last):
  File "hangouts_to_sms.py", line 18, in <module>
    titanium_output.create_output_file(conversations, self_gaia_id, OUTPUT_FILE)
  File "C:\sms\hangouts_to_sms-develop\titanium_backup_formatter.py", line 74, in create_output_file
    content_is_plain = self._is_ascii(message.content)
  File "C:\sms\hangouts_to_sms-develop\titanium_backup_formatter.py", line 176, in _is_ascii
    return len(text) == len(text.encode())
TypeError: object of type 'NoneType' has no len()
```

**Comment by JoesphG** [comment]
had looked at the suggestions in #12 but still unable to resolve @mrdehate

**Comment by chadwilcomb** [comment]
@JoesphG I was stuck in the same place you were and got through by applying the following additional steps:
1. Adding a null check to the `_is_ascii` function at line 174-6 of titanium_backup_formatter.py
```
def _is_ascii(text):
    # Returns true if the text in not None and only contains ASCII characters
    return text and len(text) == len(text.encode())
```
2. Remove any empty `<sms>` tags from output XML (by searching for `></sms>`)

**Comment by JoesphG** [comment]
Thanks Ill give it a go and see if that resolves
