### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'conversation_state'

### ISSUE THREAD

**Issue by LizzyLou817** [adein/hangouts_to_sms#19]
I am new to coding but was able to follow the instructions and run this script. I'm trying to migrate my Hangouts messages to Google Messages (I'm on Project Fi).

It returned this:

Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: /Users/xxxxxx/Downloads/hangouts_to_sms-develop/hangouts_to_sms.py 
Parsing Hangouts data file...
Traceback (most recent call last):
  File "/Users/xxxxxx/Downloads/hangouts_to_sms-develop/hangouts_to_sms.py", line 15, in <module>
    conversations, self_gaia_id = hangouts_parser.parse_input_file(HANGOUTS_JSON_FILE, YOUR_PHONE_NUMBER)
  File "/Users/xxxxxx/Downloads/hangouts_to_sms-develop/hangouts_parser.py", line 25, in parse_input_file
    for conversation_state in data.conversation_state:
AttributeError: 'Namespace' object has no attribute 'conversation_state'
>>> 

Any suggestions?

**Comment by joshklod** [comment]
Try suggestions in #8 by @onemodtwo
